import type { Event, User, Booking } from '@/types';

export const events: Event[] = [
  {
    id: '1',
    title: 'Starlight Music Festival',
    description: 'An unforgettable weekend with the biggest names in electronic and indie music. Featuring multiple stages, food trucks, and art installations.',
    date: '2024-08-15',
    time: '12:00 PM - 11:00 PM',
    location: 'Sunset Valley',
    category: 'Music',
    organizer: 'Vibe Events',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    imageHint: 'music festival',
  },
  {
    id: '2',
    title: 'Future of AI Summit',
    description: 'Join industry leaders and researchers to explore the latest advancements in artificial intelligence and machine learning.',
    date: '2024-09-10',
    time: '9:00 AM - 5:00 PM',
    location: 'Metropolis Convention Center',
    category: 'Tech',
    organizer: 'InnovateX',
    price: 499,
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    imageHint: 'tech conference',
  },
  {
    id: '3',
    title: 'Gourmet Food Fair',
    description: 'A paradise for food lovers. Sample dishes from world-renowned chefs and local culinary talents. Cooking demos and workshops available.',
    date: '2024-07-20',
    time: '11:00 AM - 9:00 PM',
    location: 'Central Park',
    category: 'Food',
    organizer: 'TasteMakers',
    price: 50,
    imageUrl: 'https://picsum.photos/seed/103/600/400',
    imageHint: 'food festival',
  },
  {
    id: '4',
    title: 'Modern Art Exhibit: Dimensions',
    description: 'Experience a journey through contemporary art, featuring sculptures, interactive installations, and digital media from artists around the globe.',
    date: '2024-07-25',
    time: '10:00 AM - 6:00 PM',
    location: 'The Modernist Gallery',
    category: 'Art',
    organizer: 'ArtFlow Curations',
    price: 25,
    imageUrl: 'https://picsum.photos/seed/104/600/400',
    imageHint: 'art exhibition',
  },
  {
    id: '5',
    title: 'Mountain Peak Marathon',
    description: 'Challenge yourself with our annual marathon through breathtaking mountain scenery. Open to all skill levels, with 5k, 10k, and full marathon options.',
    date: '2024-08-05',
    time: '7:00 AM - 2:00 PM',
    location: 'Evergreen National Park',
    category: 'Sports',
    organizer: 'Peak Performance',
    price: 75,
    imageUrl: 'https://picsum.photos/seed/105/600/400',
    imageHint: 'outdoor sport',
  },
  {
    id: '6',
    title: 'Serenity Yoga Retreat',
    description: 'A weekend of relaxation, meditation, and yoga practice in a beautiful, secluded location. All-inclusive package with healthy meals and guided sessions.',
    date: '2024-09-20',
    time: 'Starts 4:00 PM Friday',
    location: 'Tranquil Pines Resort',
    category: 'Wellness',
    organizer: 'Zen Journeys',
    price: 750,
    imageUrl: 'https://picsum.photos/seed/106/600/400',
    imageHint: 'wellness retreat',
  },
];

export const users: User[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', role: 'Admin', joinedDate: '2023-01-15' },
  { id: '2', name: 'Bob Williams', email: 'bob@example.com', role: 'Organizer', joinedDate: '2023-02-20' },
  { id: '3', name: 'Charlie Brown', email: 'charlie@example.com', role: 'User', joinedDate: '2023-03-10' },
  { id: '4', name: 'Diana Miller', email: 'diana@example.com', role: 'User', joinedDate: '2023-05-01' },
  { id: '5', name: 'Eve Davis', email: 'eve@example.com', role: 'User', joinedDate: '2023-06-18' },
];

export const bookings: Booking[] = [
    { id: '1', eventTitle: 'Starlight Music Festival', eventDate: '2024-08-15', location: 'Sunset Valley', bookingDate: '2024-06-01', status: 'Confirmed' },
    { id: '2', eventTitle: 'Future of AI Summit', eventDate: '2024-09-10', location: 'Metropolis Convention Center', bookingDate: '2024-06-05', status: 'Confirmed' },
    { id: '3', eventTitle: 'Gourmet Food Fair', eventDate: '2024-07-20', location: 'Central Park', bookingDate: '2024-06-10', status: 'Cancelled' },
    { id: '4', eventTitle: 'Serenity Yoga Retreat', eventDate: '2024-09-20', location: 'Tranquil Pines Resort', bookingDate: '2024-06-15', status: 'Pending' },
];
